## DataTypes


```{r echo=TRUE}

typeof(10.14)
typeof(1L)
typeof(10L)
typeof(1+1i)
typeof(TRUE)
typeof("JCU")
```

# Vectors
  ## Elements of same type
  ## No Row or Column Vector in R
  ## Elements can be combined with c()
  ## R is a vectorized language, operations are applied to each element automatically

# Data Types in Vector

```{r echo=TRUE}
v<- c(1,2,3,4,5,6)
typeof(v)

v<- c('1',2,3,4,5,6)
typeof(v)

v<- c(1L,2L,3L,4L,5L,6L)
typeof(v)

v<- c('TRUE','FALSE')
typeof(v)

v<- c(TRUE,FALSE,TRUE)
typeof(v)

v<- c(0,1,0,1,1,0)
typeof(v)


```



#Combining Vectors
```{r echo=TRUE}
fruits <- c("Apple", "oranges", "banana")
vegetables <- c("cabbage", "spinach", "tomatoes")
all_basket_items <- c(fruits, vegetables)
all_basket_items
#length(all_basket_items)
#sort(all_basket_items, decreasing = TRUE)


```

#Naming Vectors
```{r echo=TRUE}


#Months<- c(Jan=1, Feb=2, Mar=3)

Months <- c(1L,2L,3L,4L)
names(Months) <- c('Jan','Feb','Mar','Apr')
Months
Months ['Jan'] # referencing with names
```

#Vector Index
```{r echo=TRUE}


#Months<- c(Jan=1, Feb=2, Mar=3)

fruits <- c("Apple", "oranges", "banana")
vegetables <- c("cabbage", "spinach", "tomatoes")
all_basket_items <- c(fruits, vegetables)
#all_basket_items[4]

#Logical Index Vector: A new vector can be sliced from a given vector with a logical index vector, which has the same length as the original vector.

Logical_v<-c(TRUE,FALSE,TRUE,FALSE,TRUE,FALSE)
all_basket_items[Logical_v]

#Changing values in a vector

all_basket_items[4]<-"Red Cabbage"
all_basket_items
```


#Vector Arithmetics
```{r echo=TRUE}
a = c(1, 3, 5, 7) 
b = c(1, 2, 4, 8)

10*a
a+b
a*b

#recycling rules : longer object length should be multiple of shorter object

a = c(10, 20, 30) 
b = c(1, 2, 3, 4, 5, 6, 7, 8, 9) 
a + b 

```


#Vector repeating
```{r echo=TRUE}
a = rep(1:5, 3) 
a
a = rep(1:5, each = 3)
a
a=rep(1:5, times = 1:5)
a
a=rep(1:5, length.out = 7)
a
a=rep_len(1:5, 7)
a
```


#Vector sequences
```{r echo=TRUE}
a =seq.int(3, 12) 
a
a=3:12
a
a=seq.int(3, 12, 2)
a
a=seq.int(0.1, 0.01, -0.01)
a
seq(0, 1, length.out = 11)
seq(stats::rnorm(20)) # effectively 'along'
seq(1, 9, by = 2)     # matches 'end'
seq(1, 9, by = pi)    # stays below 'end'
seq(1, 6, by = 3)
seq(1.575, 5.125, by = 0.05)
seq(17) # same as 1:17, or even better seq_len(17)
#a = rep(1:5, each = 3)
#a
#a=rep(1:5, times = 1:5)
#a
#a=rep(1:5, length.out = 7)
#a
#a=rep_len(1:5, 7)
#a
```